<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Image_problem_user</name>
   <tag></tag>
   <elementGuidId>09fa0388-b392-46bd-9294-9a0013325cc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src='/static/media/sl-404.168b1cce.jpg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='/static/media/sl-404.168b1cce.jpg']</value>
   </webElementProperties>
</WebElementEntity>
